//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LBA_Infraestructura.Repositorios {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.4.0.0")]
    internal sealed partial class StrCadenaConexion
    {

        /// string de conexion de la base de datos a utilizar
        /// 

        public string Cadena
        {
            get => "Server=bibliotecatravel.database.windows.net; user id=server123; Password=Seguridad2023*; Database=sqlbiblioteca";

        }
    }
}
